### ISSUE TITLE
Mimiking the Hotstring-preview tooltip for a specific script

### ISSUE THREAD

**Issue by Gewerd-Strauss** [mslonik/Hotstrings#13]
Hello,

this is not an issue per se, but rather a question regarding a specific functionality.

I have a couple of files with extensive sets of specific hotstrings which for irrelevant reasons I cannot import to this application. However, especially because they are set to launch/edit/reload a specific suite of scripts, they are repetitive.

Now, your Hotstrings-application has the _very_ nice ability of dynamically showing possible hotstrings based on recent input as a tooltip.

I have tried myself at something like this a good while back, then abandoned it due to lack of time, knowledge and actual true necessity (aforementioned suite didn'r exist yet).

---

How does Hotstrings.ahk parse its hotstrings to display them dynamically? Is it possible to shadow this on a custom script? If not, what is the actual logical flowchart behind this piece of the program?

Thank you,

Sincerely,
~Gw

**Comment by mslonik** [comment]
Hi Gw,

answering your questions:

_How does Hotstrings.ahk parse its hotstrings to display them dynamically?_
It stores all definitions in the set of arrays. Next it constantly monitors user input. Based on user input it processes "short array" which is displayed to a user. Of course part of this process is related to filtering.

_Is it possible to shadow this on a custom script?_
Yes of course. This is power of open source that we can relatively easily transfer ideas between scripts / applications. 

_what is the actual logical flowchart behind this piece of the program?_
I'd suggest face-to-face communication and digging in the code.

Last, but not least. Nowadays I'm working on substantial change of input processing. I wish to leave aside "Input" method and replace it with much more clear and powerful "InputHook" method. When this task is finished I plan to release version 3.7.x as it will be major change.

Kind regards, mslonik (🐘)

**Comment by Gewerd-Strauss** [comment]
>  I'd suggest face-to-face communication and digging in the code. 

We can do so, but _right now_ I am absolutely overloaded with work, and at the beginning of of hellweek - exams are starting next week. 

So time is extremely limited right now. I just wanted to get the ball rolling already inbefore I forget _again_ to bost these questions and requests (This is all sitting on my back burner for like two months now, and I keep forgetting it :P)
