### ISSUE TITLE
"Log" Folder Should auto-create.

### ISSUE THREAD

**Issue by SalviaSage** [mslonik/Hotstrings#23]
Issue:
If we go to the "Application" tab and click on the "Open folder where the log files are located",
We get an error.

This is because the "Log" folder is not created there by default.
The "Libraries" folder is created. But the "Log" folder is not created.

So, I think you should make it so that alongside the "Libraries" folder, the "Log" folder is created as well.
It does auto-create, but only after turning on logging right now.

It's a small issue but it is a start and it is my first bug report.
Small changes like these will make this program more professional.

Thanks Maciej.

**Comment by SalviaSage** [comment]
https://i.imgur.com/8eCzW8H.png

**Comment by mslonik** [comment]
Fixed in release 3.6.4.
