### ISSUE TITLE
Bug: Variable Assignment

### ISSUE THREAD

**Issue by SalviaSage** [mslonik/Hotstrings#24]
I got this error pop up out of nowhere.
It seems that one of the variables (line 9935, 'vh' variable) isn't assigned.
Maybe it can be dummy assigned or it can be fixed in a simple way.

**Comment by SalviaSage** [comment]
https://i.imgur.com/SVBzlSg.png

**Comment by mslonik** [comment]
Fixed in https://github.com/mslonik/Hotstrings/commit/fb178861d1598897532420713001d2f297f8bb9e

**Comment by mslonik** [comment]
Fixed in release 3.6.4.
