### ISSUE TITLE
Libraries are not loading

### ISSUE THREAD

**Issue by DelevoXDG** [mslonik/Hotstrings#5]
![image](https://user-images.githubusercontent.com/43750648/113040515-890c9f00-91a1-11eb-86cd-150ffdc700a7.png)
Just installed it and there is only one single element in each library displayed in "Library Content".
Wasn't able to find anything regarding such issue.

**Comment by sivelasco** [comment]
Same issue here from weeks now. You can configure a library from scratch but stock libraries have load problems. Using the CuttingEdge is worse due to lack of GUI.
Hope the dev fix this, I think the project is very useful.

**Comment by mslonik** [comment]
Solved with stable release.
