### ISSUE TITLE
What is the intentions for these empty hotstrings in Abbreviations.CSV?

### ISSUE THREAD

**Issue by zhichaoh** [mslonik/Hotstrings#6]
﻿B0*?‖.ahk‖SI‖En‖‖only for extensions
B0*?‖.csv‖SI‖En‖‖only for extensions
B0*?‖.docx‖SI‖En‖‖only for extensions
B0*?‖.easm‖SI‖En‖‖only for extensions
B0*?‖.gif‖SI‖En‖‖
B0*?‖.pdf‖SI‖En‖‖only for extensions
B0*?‖.png‖SI‖En‖‖
B0*?‖.svg‖SI‖En‖‖only for extensions
B0*?‖.xlsx‖SI‖En‖‖only for extensions
B0*?‖.xml‖SI‖En‖‖only for extensions

**Comment by mslonik** [comment]
The intention is to not convert file extensions into capital letters. E.g. ahk is usually converted into AHK. In order to avoid e.g. "MyFileName.AHK" such additional file extensions are added to library. Now it's possible to just write "MyFileName.ahk".
